### ISSUE TITLE
Synapse collides badly as a name with matrix.org's reference server implementation 

### ISSUE THREAD

**Issue by ara4n** [phoreproject/graphene#114]
Sorry to be the bearer of bad news, but: I just stumbled across this project and I'm concerned that the name collides badly with https://github.com/matrix-org/synapse - the reference [Matrix](https://matrix.org) server implementation.  Given Matrix is in a similar space (decentralised communication) and bears a lot of similarities with blockchains (we actually use replicated Merkle trees for decentralisation), I'm worried that users might get badly confused between the two.  Matrix's Synapse even has sharding work for scalability, for instance - https://matrix.org/blog/2020/11/03/how-we-fixed-synapses-scalability.

So... given this project hasn't had that much visibility yet (e.g. only 9 github stars, relative to matrix-synapse's 6.8K) and is relatively new (matrix-synapse has been around and accelerating since 2014), I was wondering if you might consider renaming at this point to avoid future confusion?  thank you! :)

**Comment by meyer9** [comment]
Yep, we're already planning to rename it to Graphene. I'll switch the name tonight.

**Comment by meyer9** [comment]
Fixed, thanks for the report!
